workspace 'iFollowSpot'

target 'iFollowSpot' do
  use_frameworks!

  project 'iFollowSpot.xcodeproj'

  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'

  target 'iFollowSpotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iFollowSpotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
